### ISSUE TITLE
How does this compare to the old InputSimulator on codeplex?

### ISSUE THREAD

**Issue by jzabroski** [HavenDV/H.InputSimulator#1]
Hi @HavenDV , 

Found your project.  Has only 203 downloads but I imagine one day it might get over 1M downloads as it looks promising.

Was any of the logic borrowed from the old codeplex project?  The APIs look different, but the names are the same. https://archive.codeplex.com/?p=inputsimulator  This one has over 700k nuget package downloads but doesnt work on .NET Core without AssemblyResolve magics.

**Comment by HavenDV** [comment]
https://github.com/TChatzigiannakis/InputSimulatorPlus
I took this code as a basis, which has not been updated in 3 years. The license is the same, there is also a link to the project in the description of the repository.

**Comment by HavenDV** [comment]
> This one has over 700k nuget package downloads but doesnt work on .NET Core without AssemblyResolve magics.

I ported this project for personal purposes, but put it in the public domain for everyone. I use it in a .Net 5 application and it works.
