### ISSUE TITLE
ModifiedKeyStroke is not recognized by some applications

### ISSUE THREAD

**Issue by manuelmayer-dev** [HavenDV/H.InputSimulator#2]
The ModifiedKeyStroke function is not recognized by some applications like Streamlabs OBS because I guess it's too fast.

I found a dirty way to make it work for me but the ModifiedKeyStroke would be prettier. With that code it works:
`foreach (VirtualKeyCode modifierKey in modifierKeys)
{
       this.inputSimulator.Keyboard.KeyDown(modifierKey);
}

this.inputSimulator.Keyboard.KeyDown(virtualKeyCode);
Thread.Sleep(100);
this.inputSimulator.Keyboard.KeyUp(virtualKeyCode);
foreach (VirtualKeyCode modifierKey in modifierKeys)
{
       this.inputSimulator.Keyboard.KeyUp(modifierKey);
 }`

**Comment by oslboreal** [comment]
Using KeyDown(modifierKey)
KeyPress(virtualKeyCode)
and KeyUp(modifierKey)

Is it still not working?

**Comment by HavenDV** [comment]
ModifiedKeyStroke sends all keystrokes as a single message packet to the OS. This may be unexpected for some applications because there is no delay between messages.

**Comment by HavenDV** [comment]
```cs
new InputSimulator().Keyboard
           .KeyDown(VirtualKeyCode.LWIN, VirtualKeyCode.VK_R)
           .Sleep(100)
           .KeyUp(VirtualKeyCode.LWIN, VirtualKeyCode.VK_R);
```
I've also added overloads for KeyDown/KeyUp that make it easier to implement the workaround you've provided. I want to note that KeyUp will call the keys in reverse order
